#FROM debian:buster
#FROM trophime/mesa:19.0.1-buster
FROM trophime/qt5:5.11.3-buster

ARG JOBS=2

RUN apt-get -y update && \
    apt-get install -y wget && \
    apt-get autoclean

ENV ISPC_HOME=/usr/local/ispc-v${ISPC_VERSION}-linux
ENV PATH=$ISPC_HOME/:$PATH

# Install
# Add if depot is Lncmi: libopenturns-dev
RUN apt-get -y update && \
    apt-get install -y wget build-essential vim gcc g++ git subversion python3 m4 bison flex zlib1g-dev ncurses-dev libtinfo-dev libc6-dev-i386 && \
    apt-get install -y cmake clang && \
    apt-get install -y pkg-config libtbb-dev imagemagick freeglut3-dev libglfw3-dev libxmu-dev libxi-dev && \
    apt-get install -y libpng-dev libjpeg-dev libopenimageio-dev && \
    apt-get install -y cmake \
               libsqlite3-dev \
               libboost-all-dev \
               libavformat-dev \
               gcc g++ gfortran \
               libavutil-dev \
               libavcodec-dev \
               libswscale-dev \
               python3-dev \
               python3-all \
               libxext-dev \
               doxygen \
               graphviz \
               gnuplot \
               libtiff-dev \
               libpng-dev \
               libjpeg-dev \
               libxml2-dev \
               libexpat-dev \
               zlib1g-dev \
               libfreetype6-dev \
               default-libmysqlclient-dev \
               libpq-dev \
               libtheora-dev \
               libogg-dev \
               libhdf5-dev \
               libeigen3-dev \
               libnetcdf-dev \
               libnetcdf-cxx-legacy-dev \
               libglew-dev \
	       libxmu-dev \
	       libxres-dev \
	       libxcursor-dev \
	       libxcomposite-dev \
               libxft-dev \
	       libxi-dev \
	       libxpm-dev \
	       libxrandr-dev \
	       libxinerama-dev \
               libxt-dev \
               libsilo-dev \
               libutfcpp-dev \
	       libice-dev \
	       libcgns-dev \
	       libpugixml-dev \
	       liblz4-dev \
	       protobuf-c-compiler libprotobuf-c-dev \
	       protobuf-compiler libprotobuf-dev \
               libdouble-conversion-dev \ 
               tao-pegtl-dev \
	       libexodusii-dev \
	       libgdcm2-dev \
               libgl2ps-dev \
               python3-autobahn \
               python3-six \
               python3-twisted \
               python3-pygments \
               python3-sphinx \
               python3-zope.interface \
	       python3-matplotlib \
               python3-numpy
               
RUN cd /tmp && \
    export QT5PREFIX=/usr/local && \
    git clone https://gitlab.kitware.com/paraview/paraview.git && \
    cd paraview && \
    git submodule update --init --recursive && \
    cd VTK && \
    git submodule update --init --recursive && \
    cd .. && \
    mkdir -p build && \
    cd build && \
    export Qt5_DIR=/usr/local/Qt-5.11.3/lib/cmake && \
    cmake -DCMAKE_VERBOSE_MAKEFILE=ON \
        -DCMAKE_CXX_COMPILER=clang++ \
        -DCMAKE_C_COMPILER=clang \
        -DCMAKE_BUILD_TYPE=Release \
	    -DBUILD_DOCUMENTATION=ON \
        -DCMAKE_INSTALL_RPATH=/usr/local/lib/paraview \
        -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=OFF  \
        -DCMAKE_SKIP_RPATH=OFF \
        -DPARAVIEW_ENABLE_FFMPEG=ON \
	    -DPARAVIEW_ENABLE_WEB=ON \
	    -DPARAVIEW_ENABLE_CATALYST=ON \
	    -DBUILD_SHARED_LIBS=ON \
	    -DBUILD_TESTING=OFF \
	    -DVTK_USE_SYSTEM_LIBRARIES=ON \
	    -DVTK_USE_SYSTEM_VISITLIB=OFF \
        -DVTK_USE_SYSTEM_PYGMENTS=ON \
        -DVTK_USE_SYSTEM_QTTESTING=OFF \
        -DVTK_USE_SYSTEM_ICET=OFF \
        -DVTK_USE_SYSTEM_DIY2=OFF \
        -DVTK_USE_SYSTEM_XDMF2=OFF \
        -DVTK_USE_SYSTEM_GL2PS=ON \
        -DVTK_USE_SYSTEM_JSONCPP=OFF \
        -DVTK_USE_SYSTEM_LIBHARU=OFF \
        -DVTK_USE_SYSTEM_MPI4PY=OFF \
        -DVTK_BUILD_ALL_MODULE=ON \
        -DVTK_Group_Web=ON \
        -DVTK_INSTALL_LIBRARY_DIR="local/lib/paraview" \
        -DVTK_INSTALL_ARCHIVE_DIR="local/lib/paraview" \
        -DVTK_INSTALL_INCLUDE_DIR="local/include/paraview" \
        -DVTK_INSTALL_DATA_DIR="local/share/paraview" \
        -DVTK_INSTALL_DOC_DIR="local/share/doc/paraview" \
        -DVTK_INSTALL_PACKAGE_DIR="local/lib/cmake/paraview" \
        -DVTK_CUSTOM_LIBRARY_SUFFIX="" \
        -DBUILD_EXAMPLES=OFF \
        -DDOCUMENTATION_HTML_HELP=ON \
        -DPARAVIEW_INSTALL_DEVELOPMENT_FILES=ON \
        -DBUILD_DOCUMENTATION=ON \
        -DPARAVIEW_ENABLE_PYTHON=ON \
        -DPYTHON_EXECUTABLE=/usr/bin/python3 \
	    -DPARAVIEW_PLUGIN_ENABLE_AdiosReader=ON \
	    -DPARAVIEW_PLUGIN_ENABLE_EyeDomeLighting=ON \
	    -DPARAVIEW_PLUGIN_ENABLE_MobileRemoteControl=OFF \
        -DPARAVIEW_PLUGIN_ENABLE_ForceTime=ON \
	    -DPARAVIEW_PLUGIN_ENABLE_H5PartReader=ON \
	    -DPARAVIEW_PLUGIN_ENABLE_PointSprite=ON \
	    -DPARAVIEW_PLUGIN_ENABLE_SurfaceLIC=ON \
        -DPARAVIEW_PLUGIN_ENABLE_CoProcessingScriptGenerator=ON \
	    -DPARAVIEW_USE_VISITBRIDGE=ON \
	    -DEigen_DIR=/usr/include/eigen3 \
	    -DPARAVIEW_BUILD_WEB_DOCUMENTATION=ON \
	    -DVTK_RENDERING_BACKEND:STRING=OpenGL2 \
	    -DPARAVIEW_QT_VERSION=5 \
        -DVTK_INSTALL_NO_DOCUMENTATION=ON .. && \
    make -j${JOBS} && \
    make install && \
    cd /tmp/ && \
    rm -rf paraview
